// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDhgg3c-k74a0uQ-23FTaPN5lcHlPxfFFs',
    appId: '1:590805319674:web:78fb548767aa12673aae43',
    messagingSenderId: '590805319674',
    projectId: 'tugasakhir-30ad6',
    authDomain: 'tugasakhir-30ad6.firebaseapp.com',
    storageBucket: 'tugasakhir-30ad6.firebasestorage.app',
    measurementId: 'G-LXNY5PNL9G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDRSwNTl8XUJW1MzLRgWo6fttuWSh2xwYc',
    appId: '1:590805319674:android:63659a4af00cef833aae43',
    messagingSenderId: '590805319674',
    projectId: 'tugasakhir-30ad6',
    storageBucket: 'tugasakhir-30ad6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDLD2QQ7Q1KYJfUVPC16LVJi8HF0j3ebXE',
    appId: '1:590805319674:ios:c1e50646bbcc9e613aae43',
    messagingSenderId: '590805319674',
    projectId: 'tugasakhir-30ad6',
    storageBucket: 'tugasakhir-30ad6.firebasestorage.app',
    iosBundleId: 'com.example.tugasAkhir',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDLD2QQ7Q1KYJfUVPC16LVJi8HF0j3ebXE',
    appId: '1:590805319674:ios:c1e50646bbcc9e613aae43',
    messagingSenderId: '590805319674',
    projectId: 'tugasakhir-30ad6',
    storageBucket: 'tugasakhir-30ad6.firebasestorage.app',
    iosBundleId: 'com.example.tugasAkhir',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDhgg3c-k74a0uQ-23FTaPN5lcHlPxfFFs',
    appId: '1:590805319674:web:5adccec1d46b38d93aae43',
    messagingSenderId: '590805319674',
    projectId: 'tugasakhir-30ad6',
    authDomain: 'tugasakhir-30ad6.firebaseapp.com',
    storageBucket: 'tugasakhir-30ad6.firebasestorage.app',
    measurementId: 'G-83K9NC86V7',
  );
}
